<a href="https://colab.research.google.com/github/chavamoon/MachineLearningExamples/blob/main/Python/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import KFold
from sklearn.model_selection import TimeSeriesSplit

In [3]:
np.random.seed(200725)

In [5]:
X = np.array([[10,5,2], [8,3,1], [11,4,4], [10,2,2], [5,2,5], [2,3,4], [1,2,3], [12,5,3], [4,3,2], [1,2,1]])
y = np.array([1,2,1,3,1,2,1,2,3,1])

In [7]:
#K-fold
kf = KFold(n_splits=4)

for train_indexes, test_indexes in kf.split(X):
    print('train indexes: ', train_indexes, 'test indexes: ', test_indexes)
    X_train, X_test = X[train_indexes], X[test_indexes]
    y_train, y_test = y[train_indexes], y[test_indexes]
    print('train elements:\n ', X_train, y_train)
    print('test elements:\n', X_test, y_test)

train indexes:  [3 4 5 6 7 8 9] test indexes:  [0 1 2]
train elements:
  [[10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 1  2  3]
 [12  5  3]
 [ 4  3  2]
 [ 1  2  1]] [3 1 2 1 2 3 1]
test elements:
 [[10  5  2]
 [ 8  3  1]
 [11  4  4]] [1 2 1]
train indexes:  [0 1 2 6 7 8 9] test indexes:  [3 4 5]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [ 1  2  3]
 [12  5  3]
 [ 4  3  2]
 [ 1  2  1]] [1 2 1 1 2 3 1]
test elements:
 [[10  2  2]
 [ 5  2  5]
 [ 2  3  4]] [3 1 2]
train indexes:  [0 1 2 3 4 5 8 9] test indexes:  [6 7]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 4  3  2]
 [ 1  2  1]] [1 2 1 3 1 2 3 1]
test elements:
 [[ 1  2  3]
 [12  5  3]] [1 2]
train indexes:  [0 1 2 3 4 5 6 7] test indexes:  [8 9]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 1  2  3]
 [12  5  3]] [1 2 1 3 1 2 1 2]
test elements:
 [[4 3 2]
 [1 2 1]] [3 1]


In [9]:
#Temporal cross validation
tpv = TimeSeriesSplit(n_splits=5)
for train_indexes, test_indexes in tpv.split(X):
    print('train indexes: ', train_indexes, 'test indexes: ', test_indexes)
    X_train, X_test = X[train_indexes], X[test_indexes]
    y_train, y_test = y[train_indexes], y[test_indexes]
    print('train elements:\n ', X_train, y_train)
    print('test elements:\n', X_test, y_test)


train indexes:  [0 1 2 3 4] test indexes:  [5]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]] [1 2 1 3 1]
test elements:
 [[2 3 4]] [2]
train indexes:  [0 1 2 3 4 5] test indexes:  [6]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]] [1 2 1 3 1 2]
test elements:
 [[1 2 3]] [1]
train indexes:  [0 1 2 3 4 5 6] test indexes:  [7]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 1  2  3]] [1 2 1 3 1 2 1]
test elements:
 [[12  5  3]] [2]
train indexes:  [0 1 2 3 4 5 6 7] test indexes:  [8]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 1  2  3]
 [12  5  3]] [1 2 1 3 1 2 1 2]
test elements:
 [[4 3 2]] [3]
train indexes:  [0 1 2 3 4 5 6 7 8] test indexes:  [9]
train elements:
  [[10  5  2]
 [ 8  3  1]
 [11  4  4]
 [10  2  2]
 [ 5  2  5]
 [ 2  3  4]
 [ 1  2  3]
 [12  5  3]
 [ 4  3  2]] [1 2 1 3 1 2 1 2 3]
test elements:
 [[1 2 1]] [